# Generated by Django 3.1.2 on 2020-11-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isClient',
            field=models.CharField(default=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='moreInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.client'),
        ),
    ]
