# Generated by Django 3.1.2 on 2020-11-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201111_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='moreInfo',
            new_name='ifClient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isClient',
        ),
    ]
