# Generated by Django 3.1.2 on 2020-11-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201111_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('kvkNumber', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('homeAddress', models.CharField(max_length=50)),
                ('speciality', models.TextField()),
                ('postcode', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ifFreelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.freelancer'),
        ),
    ]
