# Generated by Django 3.1.2 on 2020-11-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20201111_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='kvkNumber',
            new_name='phone',
        ),
    ]
