# Generated by Django 3.1.2 on 2020-12-01 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201201_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 11, 48, 33, 242688)),
        ),
    ]
